<?php

namespace AD\FlatBundle\Repository;

/**
 * FlatImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatImageRepository extends \Doctrine\ORM\EntityRepository
{
}
