pension_list:
    path:     /
    defaults: { _controller: 'PensionBundle:Pension:list' }
    
pension_show:
    path:     /{id}
    defaults: { _controller: 'PensionBundle:Pension:show' }
    requirements:
        id: \d+
        
pension_image_delete:
    path:     /delete/image
    defaults: { _controller: 'PensionBundle:Pension:deleteImage' }

pension_image_upload:
    path:     /upload/{id}/image
    defaults: { _controller: 'PensionBundle:Pension:uploadPensionImage' }
    requirements:
        id: \d+
        
admin_pensionimage_sort:
    path:     /image/sort/{id}/{position}
    defaults: { _controller: 'PensionBundle:Pension:sort' }
    methods:  GET

pension_publish:
    path:     /publish
    defaults: { _controller: 'PensionBundle:Flat:publish' }
    
pension_pdf_details:
    path:     /pdf/details
    defaults: { _controller: 'PensionBundle:Pension:pdfDetails' }