services:
#    pension.example:
#        class: AD\PensionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    
  pension_bundle.pdf:
    class: AD\PensionBundle\Service\PdfPensionService
    public: true
    autowire: true