flat_list:
    path:     /
    defaults: { _controller: 'FlatBundle:Flat:list' }
    
flat_show:
    path:     /{id}
    defaults: { _controller: 'FlatBundle:Flat:show' }
    requirements:
        id: \d+
    
flat_image_delete:
    path:     /delete/image
    defaults: { _controller: 'FlatBundle:Flat:deleteImage' }
    
flat_image_upload:
    path:     /upload/{id}/image
    defaults: { _controller: 'FlatBundle:Flat:uploadFlatImage' }
    requirements:
        id: \d+

