services:
#    pension.example:
#        class: AD\PensionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  flat_bundle.pdf:
    class: AD\FlatBundle\Service\PdfFlatService
    public: true
    autowire: true
    
