<?php

namespace AD\CoreBundle\Repository;

/**
 * PensionImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PensionImageRepository extends \Doctrine\ORM\EntityRepository
{
}
