core_homepage:
    path: /{_locale}/
    defaults: { _controller: 'CoreBundle:Core:indexWithLocale' }
    requirements:
      _locale: en|fr|es 
      
core_homepage_wo_locale:
    path: /
    defaults: { _controller: 'CoreBundle:Core:index' }

core_project:
    path: /{_locale}/project
    defaults: { _controller: 'CoreBundle:Core:project' }

core_team:
    path: /{_locale}/team
    defaults: { _controller: 'CoreBundle:Core:team' }

core_administration:
    path: /{_locale}/administration
    defaults: { _controller: 'CoreBundle:Core:administration' }

core_terms:
    path: /{_locale}/terms
    defaults: { _controller: 'CoreBundle:Core:terms' }

#USER SECTION

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    

#Image Section
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#Pension Section
pension:
    resource: "@CoreBundle/Resources/config/routing_pension.yml"
    prefix: /{_locale}/pension
    requirements:
      _locale: en|fr|es 
#Admin section
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix: /admin
      
#Flat Section
flat:
    resource: "@CoreBundle/Resources/config/routing_flat.yml"
    prefix: /{_locale}/flat
    requirements:
      _locale: en|fr|es 
      
