flat_list_sale:
    path:     /sale
    defaults: { _controller: 'CoreBundle:Flat:listSale' }
    
flat_list_rent:
    path:     /rent
    defaults: { _controller: 'CoreBundle:Flat:listRent' }
    
flat_show:
    path:     /{id}
    defaults: { _controller: 'CoreBundle:Flat:show' }
    requirements:
        id: \d+
    
flat_image_delete:
    path:     /delete/image
    defaults: { _controller: 'CoreBundle:Flat:deleteImage' }
    
flat_image_upload:
    path:     /upload/{id}/image
    defaults: { _controller: 'CoreBundle:Flat:uploadFlatImage' }
    requirements:
        id: \d+
        
admin_flatimage_sort:
    path:     /image/sort/{id}/{position}
    defaults: { _controller: 'CoreBundle:Flat:sort' }
    methods:  GET

summer_flat_list_rent:
    path:     /summer/rent
    defaults: { _controller: 'CoreBundle:Flat:listSummerRent' }
    
summer_flat_show:
    path:     /summer/{id}
    defaults: { _controller: 'CoreBundle:Flat:showSummer' }
    requirements:
        id: \d+
        
flat_publish:
    path:     /publish
    defaults: { _controller: 'CoreBundle:Flat:publish' }
    
flat_pdf_details:
    path:     /pdf/details
    defaults: { _controller: 'CoreBundle:Flat:pdfDetails' }
    