services:

#    core.example:
#        class: GC\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  core_bundle.pdf:
    class: AD\CoreBundle\Service\PdfService
    public: true
    autowire: true
