easy_admin:
    site_name: 'Greco Inmobiliaria'
    design:
        brand_color: '#1ABC9C'
        color_scheme: 'dark'
        assets:
            favicon: '/assets/backend/favicon.png'
            css:
                #look here to find the ids for the css: https://symfony.com/doc/current/bundles/EasyAdminBundle/book/design-configuration.html
                # HTTP protocol-relative URL
                #- '//example.org/css/admin1.css'
            js:
                #Same as css
    entities:
        User:
            class: AD\UserBundle\Entity\User
            translation_domain: 'admin'
            label: user.label
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image', label: 'user.property.imageFile' }
                    - { property: 'username', label: 'user.property.username' }
                    - { property: 'email', label: 'user.property.email' }
            list:
                title: user.list.label
                max_results: '10'
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%', label: 'user.property.image' }
                    - { property: 'id', label: 'user.property.id' }
                    - { property: 'username', label: 'user.property.username' }
                    - { property: 'email', label: 'user.property.email' }
                    - { property: 'roles', label: 'user.property.roles' }
                    - { property: 'enabled', type: 'boolean', label: 'user.property.enabled' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%' }
            search: #https://symfony.com/doc/current/bundles/EasyAdminBundle/book/list-search-show-configuration.html
                fields:
                    - { property: 'username', label: 'user.property.username' }
                    - { property: 'email', label: 'user.property.email' }
        Pension:
            class: AD\PensionBundle\Entity\Pension
            translation_domain: 'admin'
            label: pension.label
            form:
                fields:
                    - { type: 'group', label: 'pension.information', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'pension.property.name' }
                    - { property: 'minimumPrice', label: 'pension.property.minimumPrice',type: 'money', type_options: { currency: 'CLP' } }
                    - { property: 'maximumPrice', label: 'pension.property.maximumPrice',type: 'money', type_options: { currency: 'CLP' } }
                    - { type: 'group', label: 'pension.images', css_class: 'col-sm-6' }
                    - { property: 'imageFile', type: 'vich_image', label: 'pension.property.imageFile' }
                    - { type: 'group', label: 'pension.description' }
                    - { property: 'description', type: 'ckeditor', label: 'pension.property.description' }
                    - { type: 'group', label: 'pension.attachment' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'AD\PensionBundle\Form\PensionImageType', by_reference: false } }
            list:
                title: pension.list.label
                max_results: '10'
                actions: 
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }  
                    - { name: 'delete', icon: 'trash', label: false }
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.pension_images%', label: 'pension.property.image' }
                    - { property: 'name', label: 'pension.property.name' }
                    - { property: 'minimumPrice',label: 'pension.property.minimumPrice' }
                    - { property: 'maximumPrice', label: 'pension.property.maximumPrice' }
                    - { property: 'images', type: 'AD\PensionBundle\Entity\PensionImage', label: 'pension.property.images', template: 'images_list.html.twig' }
            search: #https://symfony.com/doc/current/bundles/EasyAdminBundle/book/list-search-show-configuration.html
                fields:
                    - { property: 'name', label: 'pension.property.name' }
            show:
                fields:
                    - { property: 'name', label: 'pension.property.name' }
                    - { property: 'minimumPrice',label: 'pension.property.minimumPrice' }
                    - { property: 'maximumPrice', label: 'pension.property.maximumPrice' }
                    - { property: 'image', type: 'image', base_path: '%app.path.pension_images%', label: 'pension.property.image' }
                    - { property: 'description', label: 'pension.property.description' }
                    - { property: 'images', type: 'AD\PensionBundle\Entity\PensionImage', label: 'pension.property.images', template: 'images_list.html.twig' }
