liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        building_thumbnail:
            quality: 100
            filters:
                scale:
                    dim: [ 500, 410 ]
        building_show:
            quality: 100
            filters:
                thumbnail:
                    size: [300, 300]
                    # crop the input image, if required
                    mode: outbound
        building_thumbnail_bg:
            quality: 70
            filters:
                scale:
                    dim: [ 300, 210 ]
        my_banner:
            quality: 100
            filters:
                relative_resize:
                    heighten: 100
        building_list_height:
            quality: 80
            filters:
                scale:
                    dim: [ 300, 210 ]
        building_show_height:
            quality: 100
            filters:
                relative_resize:
                    heighten: 400
        rented_es:
            quality: 80
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/rented_arrow_es.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: topleft
                scale:

                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 500, 350 ]
        rented_en:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/rented_arrow_en.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: topleft
                scale:
                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 500, 350 ]
        rented_fr:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/rented_arrow_fr.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the wposition: topleft
                    position: topleft
                scale:
                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 500, 350 ]
        sold_es:
            quality: 80
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/sold_arrow_es.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: topleft
                scale:

                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 500, 350 ]
        sold_en:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/sold_arrow_en.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: topleft
                scale:
                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 500, 350 ]
        sold_fr:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/sold_arrow_fr.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the wposition: topleft
                    position: topleft
                scale:
                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 500, 350 ]
                    