liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: "/media/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web"
    filter_sets:
        cache: ~
        pension_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        my_banner:
            quality: 100
            filters:
                relative_resize:
                    heighten: 100
        pension_list_height:
            quality: 80
            filters:
                relative_resize:
                    heighten: 250
        pension_show_height:
            quality: 100
            filters:
                relative_resize:
                    heighten: 400
