liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        building_thumbnail:
            quality: 100
            filters:
                scale:
                    dim: [ 300  , 200 ]
        building_show:
            quality: 100
            filters:
                thumbnail:
                    size: [400, 400]
                    # crop the input image, if required
                    mode: outbound
                    
        thumbnail:
            quality: 70
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
        building_thumbnail_bg:
            quality: 70
            filters:
                scale:
                    dim: [ 200, 322 ]
        my_banner:
            quality: 100
            filters:
                relative_resize:
                    heighten: 100

        sold_es:
            quality: 100
            filters:
                scale:
                    dim: [ 300  , 200 ]
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/core/img/stamps/sold_es.png
                    # size of the water mark relative to the input image
                    # set the position of the watermark
                    position: center
