liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        pension_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        my_banner:
            quality: 100
            filters:
                relative_resize:
                    heighten: 100
        pension_list_height:
            quality: 80
            filters:
                relative_resize:
                    heighten: 250
        pension_show_height:
            quality: 100
            filters:
                relative_resize:
                    heighten: 400
        rented_es:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/flat/img/rented_es.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
        rented_en:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/flat/img/rented_en.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
        rented_fr:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/bundles/flat/img/rented_fr.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center