liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        index_btn_image:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 200]
                    # crop the input image, if required
                    mode: outbound
                #crop:
                 #    size: [ 500, 200 ]
                  #   start: [050, 100]
        building_thumbnail:
            quality: 100
            filters:
                scale:
                    dim: [ 300  , 200 ]
        building_show:
            quality: 100
            filters:
                thumbnail:
                    size: [400, 400]
                    # crop the input image, if required
                    mode: outbound
                    
        thumbnail:
            quality: 70
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
        building_thumbnail_bg:
            quality: 70
            filters:
                scale:
                    dim: [ 200, 322 ]
        my_banner:
            quality: 100
            filters:
                relative_resize:
                    heighten: 100
