vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix:         '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/users'
        pension_images:
            uri_prefix:         '%app.path.pension_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/pensions'
        flat_images:
            uri_prefix:         '%app.path.flat_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/flats'